import type { Review } from "./interfaces"

export const mockReviews: Review[] = [
  {
    id: "r1",
    partnerId: "p1",
    rating: 5,
    comment: "Excellent driver, very professional and on time!",
    sentiment: "positive",
    date: "2024-01-10",
    tripId: "t1",
  },
  {
    id: "r2",
    partnerId: "p1",
    rating: 5,
    comment: "Great experience, clean car and friendly service.",
    sentiment: "positive",
    date: "2024-01-08",
    tripId: "t2",
  },
  {
    id: "r3",
    partnerId: "p2",
    rating: 4,
    comment: "Good ride, but arrived a few minutes late.",
    sentiment: "neutral",
    date: "2024-01-09",
    tripId: "t3",
  },
  {
    id: "r4",
    partnerId: "p4",
    rating: 3,
    comment: "Driver seemed distracted and took a longer route.",
    sentiment: "negative",
    date: "2024-01-07",
    tripId: "t4",
  },
  {
    id: "r5",
    partnerId: "p5",
    rating: 4,
    comment: "Reliable service, always on time.",
    sentiment: "positive",
    date: "2024-01-11",
    tripId: "t5",
  },
  {
    id: "r6",
    partnerId: "p6",
    rating: 2,
    comment: "Vehicle was not clean, and driver was rude.",
    sentiment: "negative",
    date: "2024-01-06",
    tripId: "t6",
  },
  {
    id: "r7",
    partnerId: "p7",
    rating: 5,
    comment: "Fantastic service, highly recommend!",
    sentiment: "positive",
    date: "2024-01-12",
    tripId: "t7",
  },
  {
    id: "r8",
    partnerId: "p8",
    rating: 3,
    comment: "Average trip, nothing special.",
    sentiment: "neutral",
    date: "2024-01-05",
    tripId: "t8",
  },
  {
    id: "r9",
    partnerId: "p9",
    rating: 4,
    comment: "Punctual and efficient, good experience.",
    sentiment: "positive",
    date: "2024-01-10",
    tripId: "t9",
  },
  {
    id: "r10",
    partnerId: "p10",
    rating: 1,
    comment: "Terrible service, driver cancelled last minute.",
    sentiment: "negative",
    date: "2024-01-04",
    tripId: "t10",
  },
  {
    id: "r11",
    partnerId: "p11",
    rating: 5,
    comment: "The best driver I've had, very safe and courteous.",
    sentiment: "positive",
    date: "2024-01-13",
    tripId: "t11",
  },
  {
    id: "r12",
    partnerId: "p12",
    rating: 4,
    comment: "Good overall, but the car could be cleaner.",
    sentiment: "neutral",
    date: "2024-01-07",
    tripId: "t12",
  },
  {
    id: "r13",
    partnerId: "p13",
    rating: 1,
    comment: "Unacceptable delays and poor communication.",
    sentiment: "negative",
    date: "2024-01-03",
    tripId: "t13",
  },
  {
    id: "r14",
    partnerId: "p14",
    rating: 5,
    comment: "Always a pleasant ride, very reliable.",
    sentiment: "positive",
    date: "2024-01-11",
    tripId: "t14",
  },
  {
    id: "r15",
    partnerId: "p15",
    rating: 3,
    comment: "Driver was okay, but seemed a bit tired.",
    sentiment: "neutral",
    date: "2024-01-09",
    tripId: "t15",
  },
]